
name: java_cache
version: 0.0.1
language: java
description: Java cache
public: true
tags:
  - java
  - cache
inputs:
  - name: FLOW_ENABLE_CACHE
    editable: true
    options:
      - true=TRUE
      - false=FALSE
    default: 'TRUE'
  - name: ENABLE_GRADLE_CACHE
    editable: true
    options:
      - true=TRUE
      - false=FALSE
    default: 'false'
  - name: ENABLE_MAVEN_CACHE
    editable: false
    options:
      - true=TRUE
      - false=FALSE
    default: 'TRUE'
  - name: FLOW_VERSION
    editable: false
  - name: FLOW_PROJECT_ID
    editable: false
outputs:
  - name: FLOW_ENABLE_CACHE
script_path: ./run.sh  
  
template: |  
  
  
