
name: java_cache
version: 0.0.1
language: java
description: Java cache
public: true
tags:
  - java
  - cache
inputs:
  - name: FLOW_ENABLE_CACHE
    editable: true
    options:
      - true=TRUE
      - false=FALSE
    default: 'TRUE'
outputs:
  - name: FLOW_ENABLE_CACHE
script_path: ./run.sh  
  
template: |  
  
  