
name: java_cache
version: 0.0.1
language: java
description: Java cache
public: true
tags:
  - java
  - cache
inputs:
  - name: FLOW_ENABLE_CACHE
    editable: true
    desc_cn: "开启java缓存"
    desc_en: "Enable java cache"
    options:
      - true=TRUE
      - false=FALSE
    default: 'TRUE'
outputs:
  - name: FLOW_ENABLE_CACHE
script_path: ./run.sh  
  
template: |  
  
  